title: Blog Bibliotheks- und Archivinformatik
author: Tamara
# email: tamara.maechler@stud.fhgr.ch
description: > # this means to ignore newlines until "baseurl:"
  Lerntagebuch im Kurs Bibliotheks- und Archivinformatik HS2020/2021

# social links
github_username: LillaNord # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
